version: '3.8'

services:
  subscription_service:
    container_name: "subscription_service"
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - subscription_db

  subscription_db:
    image: postgres:latest
    container_name: "subscription_db"
    env_file:
      - .env
    volumes:
      - ./config/pg:/etc/postgres