app:
  name: "${APP_NAME}"
  version: "${APP_VERSION}"
  log_level: "${LOG_LEVEL}"
http:
  host: "${HTTP_HOST}"
  port: "${HTTP_PORT}"
pg:
  user: "${POSTGRES_USER}"
  password: "${POSTGRES_PASSWORD}"
  host: "${POSTGRES_HOST}"
  port: "${POSTGRES_PORT}"
  database: "${POSTGRES_DB}"
  migrations_path: "file://config/pg/migrations"